apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: f2-privesc-template
  title: F2 PrivEsc Test
  description: Dispara workflow github como a integração
spec:
  owner: guest
  type: service
  parameters:
    - title: Inputs
      required: [targetRepo]
      properties:
        targetRepo:
          title: Repo alvo
          type: string
          default: "github.com?owner=Skysz4&repo=skyscbot-f2-test"
  steps:
    - id: dispatch
      name: Dispatch workflow
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.targetRepo }}
        workflowId: dispatch.yml
        branchOrTagName: main
        workflowInputs:
          payload: "F2-PRIVESC-PROOF"
